### ISSUE TITLE
Maestro command fails for multiple environment variables

### ISSUE THREAD

**Issue by adamdanielczyk** [mobile-dev-inc/bitrise-step-maestro-cloud-upload#12]
I have the Bitrise step defined like this:

```
- maestro-cloud-upload@1:
    inputs:
      - workspace: workspace-name
      - api_key: $MAESTRO_API_KEY
      - app_file: $BITRISE_APK_PATH
      - mapping_file: $BITRISE_MAPPING_PATH
      - env: |-
          ONE=var1
          TWO=var2
```

which results in this error:

```
+ maestro cloud --apiKey [REDACTED] --mapping /bitrise/deploy/mapping.txt -e ONE=var1 TWO=var2 /bitrise/deploy/name.apk workspace-name
Missing required parameters: '--app-file', '--flows'. Example: maestro cloud --app-file <path> --flows <path>
```

defining env params like this does not work either:

```
- env: "ONE=var1\nTWO=var2"
```

but like this works just fine:

```
- env: ONE=var1\nTWO=var2
```

not sure if the 2 failing cases above should be supported but for me it was not super clear from the docs what's the correct format
